### ISSUE TITLE
Erro ao cadastrar um usuário no banco de dados

### ISSUE THREAD

**Issue by anvitrola** [anvitrola/doarte-api#10]
Embora apareça isso aqui no console quando eu faço um POST request, o usuário não é cadastrado porque  diz que o ID está nulo, como vocês podem ver no print do insomnia. 😥
```
Executing (default): SELECT "id", "email", "name", "password", "amout_money", "createdAt", "updatedAt" FROM "Users" AS "Users" WHERE "Users"."email" = 'vitoria@email.com' LIMIT 1;
"Users" ("id","email","password","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5) RETURNING "id","email","name","password","amout_money","createdAt","updatedAt";
Executing (default): SELECT "id", "email", "name", "password", "amout_money", "createdAt", "updatedAt" FROM "Users" AS "Users" WHERE "Users"."email" = 'vitoria@email.com' LIMIT 1;
Executing (default): INSERT INTO "Users" ("id","email","name","password","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING "id","email","name","password","amout_money","createdAt","updatedAt";
```

![image](https://user-images.githubusercontent.com/62806299/117547818-0ed50300-b008-11eb-8cb7-5541865c7e9c.png)

**Comment by RafaelVi** [comment]
Aconteceram basicamente duas coisas: nosso model exigia que inseríssemos o id manualmente em vez de omiti-lo por causa do autoIncrement, a solução foi remover o id da model pois o sequelize consegue fazer isso automaticamente.
Também consertei o amount_money que não estava recebendo o valor inicial de 1000 unidades pois o nome da model estava errado.
![image](https://user-images.githubusercontent.com/43658933/117553798-e65e0080-b029-11eb-9c1f-a38e6cfc0ee1.png)
![image](https://user-images.githubusercontent.com/43658933/117553816-0392cf00-b02a-11eb-9cc4-bdc670a65165.png)
